### ISSUE TITLE
Add native Shortcut support for tiling windows

### ISSUE THREAD

**Issue by nils-se** [UbuntuBudgie/window-shuffler#1]
Hey,

I just recently stumbled upon window-shuffler. As a normal user you don't notice it is already installed. Is this on purpose? I really like the tool but missed one thing: In Ubuntu Budgie 18.04 there was no nogui-option, so I grabbed the files here and put them in the directory window-shuffler instead. With the nogui-version I was able to make shortcuts for tiling windows in quarters.

Example:

Strg+Shift+1 -> /usr/share/budgie-desktop/windowshuffler/shuffler_nogui 2 2 0 0
puts the active window in the top left quarter. It's a lot faster then Super+S and mouse-click on the quarter. It works like a charm.

Maybe you could add this functionality, because I think a lot of people will like it.

Thanks for the great work!

**Comment by Jacob-Vlijm** [comment]
I agree with you shuffler no-gui could add to default functionality. We had a discussion on it a while ago on the shortcuts we could use: https://github.com/UbuntuBudgie/budgie-desktop-environment/issues/96. Feel free to join in.

**Comment by fossfreedom** [comment]
ok - as discussed ctrl+alt 5 probably needs to toggle maximisation

maybe call shuffler like

    shuffler_nogui minmax

rather than using numbers.

So for the current focussed window determine if the window is maximised - if it isn't - maximise it otherwise unmaximise it.

https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html#Gtk.Window.is_maximized

Note - this change will hold up the package upload because we are using hard-coded keyboard shortcuts.

**Comment by Jacob-Vlijm** [comment]
This would require an additional wrapper, since shuffler and/or nogui does not use maximize/unmaximize. It just sets the window in a 1x1 grid.

**Comment by Jacob-Vlijm** [comment]
...wait, I can simply set it as condition on the nogui- module.
